version: '2'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - '1234:3000'
    command: /bin/sh --verbose -c 'yarn install && yarn dev'
    volumes:
      - ./frontend:/app

  gitea:
    build:
      context: gitea
      dockerfile: Dockerfile.gitea.dev
    ports:
      - '3333:3000'
      - '2222:22'
    command: /bin/bash --verbose -c 'make build && cp gitea /app/gitea/ && /usr/bin/entrypoint'

  nginx:
    volumes:
      - ./frontend:/srv/frontend

  processor:
    build:
      context: processor/
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '5000:5000'
    command: /bin/bash --verbose -c 'yarn install && yarn dev'
    volumes:
      - ./processor:/app
      - /app/node_modules
