version: '2'

services:
  frontend:
    command: /bin/sh --verbose -c "yarn install && yarn dev"
    environment:
      - NODE_ENV=development
      - KITSPACE_GITEA_URL=${KITSPACE_SCHEME}://gitea.${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}
      - KITSPACE_PROCESSOR_URL=${KITSPACE_SCHEME}://processor.${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}
      - INDEX_ISR_INTERVAL=${INDEX_ISR_INTERVAL}
      - USER_ISR_INTERVAL=${USER_ISR_INTERVAL}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /etc/hosts:/etc/hosts
    depends_on:
      - gitea

  gitea:
    environment:
      - ROOT_URL=${KITSPACE_SCHEME}://gitea.${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}/
      - USER_UID=1000
      - USER_GID=1000
      - SECRET_KEY=${GITEA_SECRET_KEY}
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./gitea:/go/src/code.gitea.io/gitea
    depends_on:
      - postgres

  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitea
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  nginx:
    command: "/bin/bash --verbose -c \"sed -e 's/@MAX_FILE_SIZE/${MAX_FILE_SIZE}/g' -e 's/@KITSPACE_DOMAIN/${KITSPACE_DOMAIN}/g' -e 's/@KITSPACE_URL/${KITSPACE_SCHEME}:\\\\/\\\\/${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}/g' /etc/nginx/conf.d/kitspace.template > /etc/nginx/conf.d/default.conf && /opt/command\""
    depends_on:
      - frontend
      - gitea
    image: kitspace/nginx-certbot-plugin:latest
    ports:
      - '${KITSPACE_DEV_PORT}:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./frontend:/srv/frontend


  processor:
    environment:
      - ALLOWED_CORS_DOMAINS=${KITSPACE_SCHEME}://${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}
      - LOG_LEVEL=info
    volumes:
      - ./volumes/gitea/git/repositories:/repositories
      - ./volumes/processor:/data
      - ./processor:/app
      - /app/node_modules
