- name: Ensure docker and docker-compose is installed
  become: true
  apt:
    pkg:
      - docker.io
      - docker-compose
    state: present
    update_cache: true

- name: Ensure '{{ ansible_user_id }}' is in 'docker' group
  become: true
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: true
