name: auto-merge
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.event.pull_request.state }}'
      - run: echo '${{ github.event.pull_request.draft }}'
      - uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false
          fetch-depth: 0
      - run: 'curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls" | jq'
      - run: git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" 'HEAD:dev' --force;
