name: Auto merge
# ensure we have write permission to issues for external pull requests (e.g. dependabot)
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  auto-merge:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          # bit confused about what credentials it normally persists and why
          # they don't work for us, but turning this to false works with what
          # we do below
          persist-credentials: false
          # 0 means fetch all commits, which we need for merging
          fetch-depth: 0
      - run: 'scripts/merge_open_pull_requests.py "${{ secrets.GITHUB_TOKEN }}"'
      - run: git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" 'HEAD:review' --force;
