name: Trigger auto-merge
on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  auto-merge:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: actions-auto-merge
          # bit confused about what credentials it normally persists and why
          # they don't work for us, but turning this to false works from experience
          persist-credentials: false
          # 0 means fetch all commits, which we need for merging
          fetch-depth: 0
      - run: 'scripts/auto_merge.py "${{ secrets.GITHUB_TOKEN }}"'
      # we use the AUTO_MERGE_BOT_TOKEN personal access token instead of
      # GITHUB_TOKEN so that the push triggers subsequent github action
      # workflows
      - run: git push "https://${{ secrets.AUTO_MERGE_BOT_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" 'HEAD:review' --force;
