name: Lint processor

on: [push]

jobs:
  lint_frontend:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2
      - run: 'cd processor && yarn install'
      - run: 'cd processor && yarn lint'
      - run: 'cd processor && yarn tsc'
